version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aad-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: aaddb
    ports:
      - "5432:5432"
    volumes:
      - aad-pgdata:/var/lib/postgresql/data

volumes:
  aad-pgdata:
