imagePullSecrets: []
replicaCount: 1

image:
  repository: agent-as-data-be
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  hamsPort: 8079

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

env: []
volumeMounts: []
volumes: []
podAnnotations: {}

config: {}
