database:
  url: "postgres://postgres:mysecretpassword@localhost:5432/aaddb"
  max_connections: 5

webservice:
  address: "0.0.0.0:8080"

hams:
  name: "aad-be"
  version: "0.1.0"
  port: 8079

debugging:
  environment: "development"
  log_level: "info"
