---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agent-as-data
  namespace: agent-as-data-dev
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/agent-as-data/helm/agent-as-data
  secretRef:
    name: ghcr-docker-auth
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main-*
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-as-data-be
  namespace: agent-as-data-dev
spec:
  chartRef:
    kind: OCIRepository
    name: agent-as-data
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/agent-as-data-be
      tag: main
      pullPolicy: Always
    imagePullSecrets:
      - name: ghcr-docker-auth
    config:
      database:
        url:
          url: postgresql://aad-postgres:5432/aaddb
          username_file: persistence/db/connection/username
          password_file: persistence/db/connection/password
        max_connections: 5
      webservice:
        address: "0.0.0.0:8080"
        api_prefix: "/api"
      llm:
        ollama_url: "http://ollama.k8s:80"
        model: "qwen2.5-coder:14b"
        timeout_secs: 120
      debugging:
        environment: "development"
        log_level: "info"
    volumes:
      - name: secrets
        projected:
          sources:
            - secret:
                name: db0-aad-user
                items:
                  - key: username
                    path: persistence/db/connection/username
                  - key: password
                    path: persistence/db/connection/password
    volumeMounts:
      - name: secrets
        mountPath: /etc/aad-be/secrets
