---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agent-as-data
  namespace: agent-as-data-dev
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/agent-as-data/helm/agent-as-data
  secretRef:
    name: ghcr-docker-auth
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main-*
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agent-as-data-be
  namespace: agent-as-data-dev
spec:
  chartRef:
    kind: OCIRepository
    name: agent-as-data
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/agent-as-data-be
      tag: main
      pullPolicy: Always
    config:
      database:
        url: "postgres://postgres:mysecretpassword@aad-postgres:5432/aaddb"
