---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dev-service
  namespace: agent-as-data-dev
  labels:
    release: prometheus-stack
  annotations: {}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - agent-as-data
          - nginx-view
  endpoints:
    - port: http-envoy-prom # Matches the name of the port in your POD
      path: /stats/prometheus
      interval: 30s
